### ISSUE TITLE
Name suggestion

### ISSUE THREAD

**Issue by unixorn** [schanur/shell-status-prompt#1]
How about Aftermath?

**Comment by schanur** [comment]
@unixorn 

Wow. That is exactly what I was looking for. I will rename the repo on the weekend. Do you want to get named/linked in a credits section in the README.md?

Thank you very much!

**Comment by unixorn** [comment]
Sure. Let me know when it's renamed and I'll add it to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins)

**Comment by schanur** [comment]
@unixorn

I renamed the repository to https://github.com/schanur/aftermath

**Comment by unixorn** [comment]
Added, thanks!
